version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartgondola_db
    ports:
      - "${DB_PORT}:5432" # Pega a porta do .env (8080 ou 5432)
    environment:
      - POSTGRES_USER=${DB_USER}     # Lê DB_USER do .env
      - POSTGRES_PASSWORD=${DB_PASS} # Lê DB_PASS do .env
      - POSTGRES_DB=${DB_NAME}       # Lê DB_NAME do .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartgondola-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - smartgondola-network

volumes:
  postgres_data:

networks:
  smartgondola-network:
    driver: bridge